name:                IntuitionisticTheoremProver
version:             0.1.0.0
github:              "andrewppar/IntuitionisticTheoremProver"
license:             BSD3
author:              "Andrew Parisi"
maintainer:          "andrew.p.parisi@gmail.com"
copyright:           "2020 Andrew Parisi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/andrewppar/IntuitionisticTheoremProver#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  IntuitionisticTheoremProver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IntuitionisticTheoremProver

tests:
  IntuitionisticTheoremProver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IntuitionisticTheoremProver
